spring:
  datasource:
    url: jdbc:h2:mem:banking
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
management:
  endpoint:
    metrics:
      enabled: true